//! Braid group B_n structure.
//!
//! Provides the group-level context including strand count,
//! Artin presentation, and group-theoretic properties.

use crate::braid::Braid;
use crate::generator::Generator;

/// The braid group B_n on n strands.
///
/// # Examples
///
/// ```
/// use braid_group_rs::group::BraidGroup;
///
/// let b3 = BraidGroup::new(3);
/// assert_eq!(b3.n_strands(), 3);
/// assert_eq!(b3.n_generators(), 2);
/// ```
#[derive(Debug, Clone)]
pub struct BraidGroup {
    /// Number of strands.
    n: usize,
}

impl BraidGroup {
    /// Create the braid group B_n.
    ///
    /// # Panics
    ///
    /// Panics if n < 2.
    pub fn new(n: usize) -> Self {
        assert!(n >= 2, "Braid group requires at least 2 strands");
        Self { n }
    }

    /// Get the number of strands.
    pub fn n_strands(&self) -> usize {
        self.n
    }

    /// Get the number of Artin generators (n-1).
    pub fn n_generators(&self) -> usize {
        self.n - 1
    }

    /// Get all Artin generators σ_1, ..., σ_{n-1}.
    pub fn generators(&self) -> Vec<Generator> {
        (1..self.n).map(|i| Generator::sigma(i as i32)).collect()
    }

    /// Create the identity braid.
    pub fn identity(&self) -> Braid {
        Braid::identity(self.n)
    }

    /// Create a braid from indices.
    pub fn braid_from_indices(&self, indices: &[i32]) -> Braid {
        Braid::from_indices(self.n, indices)
    }

    /// Create the generator σ_i.
    ///
    /// # Panics
    ///
    /// Panics if i is not in {1, ..., n-1}.
    pub fn sigma(&self, i: usize) -> Generator {
        assert!(i >= 1 && i < self.n, "Generator index out of range");
        Generator::sigma(i as i32)
    }

    /// Create σ_i^{-1}.
    pub fn sigma_inv(&self, i: usize) -> Generator {
        assert!(i >= 1 && i < self.n);
        Generator::sigma_inv(i as i32)
    }

    /// Check the braid relation: σ_i σ_j = σ_j σ_i if |i - j| > 1.
    pub fn check_commuting_relation(&self, i: usize, j: usize) -> bool {
        assert!(i >= 1 && i < self.n && j >= 1 && j < self.n);
        if (i as i32 - j as i32).unsigned_abs() > 1 {
            // They should commute: σ_i σ_j = σ_j σ_i
            let lhs = self.braid_from_indices(&[i as i32, j as i32]);
            let rhs = self.braid_from_indices(&[j as i32, i as i32]);
            // They should have the same reduced form (permutation)
            lhs.permutation() == rhs.permutation()
        } else {
            false
        }
    }

    /// Verify the Artin braid relation: σ_i σ_{i+1} σ_i = σ_{i+1} σ_i σ_{i+1}.
    pub fn check_braid_relation(&self, i: usize) -> bool {
        assert!(i >= 1 && i + 1 < self.n);
        let lhs = self.braid_from_indices(&[i as i32, (i + 1) as i32, i as i32]);
        let rhs = self.braid_from_indices(&[(i + 1) as i32, i as i32, (i + 1) as i32]);
        // Same permutation
        lhs.permutation() == rhs.permutation()
    }

    /// Compute the center of B_n.
    ///
    /// The center of B_n (for n ≥ 3) is generated by (σ_1 σ_2 ... σ_{n-1})^n.
    /// For n = 2, the center is generated by σ_1^2.
    pub fn center_generator(&self) -> Braid {
        let mut word = Vec::new();
        for _ in 0..self.n {
            for i in 1..self.n {
                word.push(i as i32);
            }
        }
        self.braid_from_indices(&word)
    }

    /// Check if the group is abelian (only B_2 is abelian).
    pub fn is_abelian(&self) -> bool {
        self.n == 2
    }

    /// Get the order of the center generator.
    /// The center is infinite, but the full twist has order ∞ as an element.
    /// Returns `None` (infinite order).
    pub fn center_order(&self) -> Option<usize> {
        None // Infinite
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_braid_group_new() {
        let bg = BraidGroup::new(3);
        assert_eq!(bg.n_strands(), 3);
        assert_eq!(bg.n_generators(), 2);
    }

    #[test]
    fn test_generators() {
        let bg = BraidGroup::new(4);
        let gens = bg.generators();
        assert_eq!(gens.len(), 3);
        assert_eq!(gens[0].index(), 1);
        assert_eq!(gens[1].index(), 2);
        assert_eq!(gens[2].index(), 3);
    }

    #[test]
    fn test_identity() {
        let bg = BraidGroup::new(3);
        let id = bg.identity();
        assert!(id.is_reduced_identity());
    }

    #[test]
    fn test_sigma() {
        let bg = BraidGroup::new(3);
        assert_eq!(bg.sigma(1).index(), 1);
        assert_eq!(bg.sigma_inv(1).index(), -1);
    }

    #[test]
    fn test_commuting_relation() {
        let bg = BraidGroup::new(4);
        assert!(bg.check_commuting_relation(1, 3)); // |1-3| = 2 > 1
    }

    #[test]
    fn test_braid_relation_b3() {
        let bg = BraidGroup::new(3);
        assert!(bg.check_braid_relation(1));
    }

    #[test]
    fn test_braid_relation_b4() {
        let bg = BraidGroup::new(4);
        assert!(bg.check_braid_relation(1));
        assert!(bg.check_braid_relation(2));
    }

    #[test]
    fn test_center_generator() {
        let bg = BraidGroup::new(3);
        let center = bg.center_generator();
        // (σ_1 σ_2)^3 = [1,2,1,2,1,2]
        assert_eq!(center.word().to_indices(), vec![1, 2, 1, 2, 1, 2]);
        assert!(center.is_pure());
    }

    #[test]
    fn test_is_abelian() {
        assert!(BraidGroup::new(2).is_abelian());
        assert!(!BraidGroup::new(3).is_abelian());
    }

    #[test]
    fn test_center_order_infinite() {
        let bg = BraidGroup::new(3);
        assert!(bg.center_order().is_none());
    }

    #[test]
    #[should_panic(expected = "at least 2 strands")]
    fn test_too_few_strands() {
        BraidGroup::new(1);
    }

    #[test]
    fn test_braid_from_indices() {
        let bg = BraidGroup::new(4);
        let b = bg.braid_from_indices(&[1, 2, 3]);
        assert_eq!(b.word().to_indices(), vec![1, 2, 3]);
    }
}
